import React, { useState, useEffect } from 'react';
import axios from 'axios';

const Payroll = () => {
  const [salarySlips, setSalarySlips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedSlip, setSelectedSlip] = useState(null);

  useEffect(() => {
    fetchSalarySlips();
  }, []);

  const fetchSalarySlips = async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const response = await axios.get('http://localhost:5000/api/payroll/my-slips', {
        headers: { Authorization: `Bearer ${token}` }
      });

      console.log('Full Response:', response.data);
console.log('Success?', response.data.success);
console.log('Slips:', response.data.slips);

if (response.data.success) {
  setSalarySlips(response.data.slips);
}
    } catch (error) {
      console.error('Error fetching salary slips:', error);
      alert('Failed to load salary slips');
    } finally {
      setLoading(false);
    }
  };

  const formatMonth = (monthStr) => {
    const [year, month] = monthStr.split('-');
    const date = new Date(year, month - 1);
    return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  };

  const formatCurrency = (amount) => {
    return '₹' + parseFloat(amount).toLocaleString('en-IN', { minimumFractionDigits: 2 });
  };

  const viewDetails = (slip) => {
    setSelectedSlip(slip);
  };

  const closeDetails = () => {
    setSelectedSlip(null);
  };

  const downloadPDF = (slip) => {
    // Generate simple text-based salary slip
    const content = `
=====================================
        SALARY SLIP
=====================================
Month: ${formatMonth(slip.month)}
Status: ${slip.status}
Generated: ${new Date(slip.generated_date).toLocaleDateString()}

-------------------------------------
EARNINGS
-------------------------------------
Basic Salary:        ${formatCurrency(slip.basic_salary)}
Allowances:          ${formatCurrency(slip.allowances)}
Overtime (${slip.overtime_hours}hrs): ${formatCurrency(slip.overtime_amount)}
                     ---------------
Gross Salary:        ${formatCurrency(slip.gross_salary)}

-------------------------------------
DEDUCTIONS
-------------------------------------
Absent Days: ${slip.absent_days}
Late Days: ${slip.late_days}
Half Days: ${slip.half_days}
Total Deductions:    ${formatCurrency(slip.deductions)}

-------------------------------------
NET SALARY:          ${formatCurrency(slip.net_salary)}
=====================================
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `salary_slip_${slip.month}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div style={styles.container}>
        <div style={styles.loading}>Loading salary slips...</div>
      </div>
    );
  }

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>💰 My Salary Slips</h1>
        <p style={styles.subtitle}>View and download your salary slips</p>
      </header>

      {salarySlips.length === 0 ? (
        <div style={styles.emptyState}>
          <div style={styles.emptyIcon}>📄</div>
          <h3>No Salary Slips Yet</h3>
          <p>Your salary slips will appear here once generated by admin</p>
        </div>
      ) : (
        <div style={styles.slipGrid}>
          {salarySlips.map((slip) => (
            <div key={slip.payroll_id} style={styles.slipCard}>
              <div style={styles.slipHeader}>
                <h3 style={styles.monthTitle}>{formatMonth(slip.month)}</h3>
                <span style={{
                  ...styles.statusBadge,
                  backgroundColor: slip.status === 'Paid' ? '#10b981' : slip.status === 'Generated' ? '#3b82f6' : '#6b7280'
                }}>
                  {slip.status}
                </span>
              </div>

              <div style={styles.slipBody}>
                <div style={styles.salaryRow}>
                  <span style={styles.label}>Gross Salary:</span>
                  <span style={styles.value}>{formatCurrency(slip.gross_salary)}</span>
                </div>
                <div style={styles.salaryRow}>
                  <span style={styles.label}>Deductions:</span>
                  <span style={{...styles.value, color: '#ef4444'}}>- {formatCurrency(slip.deductions)}</span>
                </div>
                <div style={{...styles.salaryRow, ...styles.netSalary}}>
                  <span style={styles.label}>Net Salary:</span>
                  <span style={{...styles.value, fontSize: '20px', fontWeight: 'bold'}}>
                    {formatCurrency(slip.net_salary)}
                  </span>
                </div>

                <div style={styles.attendanceInfo}>
                  <div style={styles.attendanceItem}>
                    <span>Present: {slip.present_days}</span>
                  </div>
                  <div style={styles.attendanceItem}>
                    <span>Absent: {slip.absent_days}</span>
                  </div>
                  <div style={styles.attendanceItem}>
                    <span>Late: {slip.late_days}</span>
                  </div>
                  <div style={styles.attendanceItem}>
                    <span>Half: {slip.half_days}</span>
                  </div>
                </div>
              </div>

              <div style={styles.slipFooter}>
                <button 
                  onClick={() => viewDetails(slip)}
                  style={styles.viewButton}
                >
                  View Details
                </button>
                <button 
                  onClick={() => downloadPDF(slip)}
                  style={styles.downloadButton}
                >
                  📥 Download
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Details Modal */}
      {selectedSlip && (
        <div style={styles.modalOverlay} onClick={closeDetails}>
          <div style={styles.modal} onClick={(e) => e.stopPropagation()}>
            <div style={styles.modalHeader}>
              <h2>Salary Slip Details</h2>
              <button onClick={closeDetails} style={styles.closeButton}>✕</button>
            </div>
            
            <div style={styles.modalBody}>
              <div style={styles.detailSection}>
                <h3 style={styles.sectionTitle}>📅 Period</h3>
                <p>{formatMonth(selectedSlip.month)}</p>
              </div>

              <div style={styles.detailSection}>
                <h3 style={styles.sectionTitle}>💵 Earnings</h3>
                <div style={styles.detailRow}>
                  <span>Basic Salary:</span>
                  <span>{formatCurrency(selectedSlip.basic_salary)}</span>
                </div>
                <div style={styles.detailRow}>
                  <span>Allowances:</span>
                  <span>{formatCurrency(selectedSlip.allowances)}</span>
                </div>
                <div style={styles.detailRow}>
                  <span>Overtime ({selectedSlip.overtime_hours} hrs):</span>
                  <span>{formatCurrency(selectedSlip.overtime_amount)}</span>
                </div>
                <div style={{...styles.detailRow, fontWeight: 'bold', borderTop: '2px solid #e5e7eb', paddingTop: '8px'}}>
                  <span>Gross Salary:</span>
                  <span>{formatCurrency(selectedSlip.gross_salary)}</span>
                </div>
              </div>

              <div style={styles.detailSection}>
                <h3 style={styles.sectionTitle}>📉 Deductions</h3>
                <div style={styles.detailRow}>
                  <span>Absent Days ({selectedSlip.absent_days}):</span>
                  <span style={{color: '#ef4444'}}>Deducted</span>
                </div>
                <div style={styles.detailRow}>
                  <span>Late Days ({selectedSlip.late_days}):</span>
                  <span style={{color: '#ef4444'}}>Penalty Applied</span>
                </div>
                <div style={styles.detailRow}>
                  <span>Half Days ({selectedSlip.half_days}):</span>
                  <span style={{color: '#ef4444'}}>Deducted</span>
                </div>
                <div style={{...styles.detailRow, fontWeight: 'bold', borderTop: '2px solid #e5e7eb', paddingTop: '8px'}}>
                  <span>Total Deductions:</span>
                  <span style={{color: '#ef4444'}}>{formatCurrency(selectedSlip.deductions)}</span>
                </div>
              </div>

              <div style={styles.netSalaryBox}>
                <h3>Net Salary</h3>
                <div style={styles.finalAmount}>{formatCurrency(selectedSlip.net_salary)}</div>
              </div>

              {selectedSlip.paid_date && (
                <div style={styles.paidInfo}>
                  ✅ Paid on {new Date(selectedSlip.paid_date).toLocaleDateString()}
                </div>
              )}
            </div>

            <div style={styles.modalFooter}>
              <button onClick={() => downloadPDF(selectedSlip)} style={styles.downloadButtonLarge}>
                📥 Download Slip
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const styles = {
  container: {
    padding: '20px',
    maxWidth: '1200px',
    margin: '0 auto',
    fontFamily: 'Arial, sans-serif',
  },
  header: {
    marginBottom: '30px',
    textAlign: 'center',
  },
  title: {
    fontSize: '32px',
    color: '#1f2937',
    margin: '0 0 10px 0',
  },
  subtitle: {
    fontSize: '16px',
    color: '#6b7280',
    margin: 0,
  },
  loading: {
    textAlign: 'center',
    padding: '50px',
    fontSize: '18px',
    color: '#6b7280',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    backgroundColor: '#f9fafb',
    borderRadius: '12px',
    border: '2px dashed #d1d5db',
  },
  emptyIcon: {
    fontSize: '64px',
    marginBottom: '20px',
  },
  slipGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
    gap: '20px',
  },
  slipCard: {
    backgroundColor: 'white',
    borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    overflow: 'hidden',
    transition: 'transform 0.2s, box-shadow 0.2s',
    cursor: 'pointer',
  },
  slipHeader: {
    padding: '20px',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  monthTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: 'bold',
  },
  statusBadge: {
    padding: '4px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: 'bold',
    backgroundColor: '#10b981',
  },
  slipBody: {
    padding: '20px',
  },
  salaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '10px 0',
    borderBottom: '1px solid #e5e7eb',
  },
  label: {
    color: '#6b7280',
    fontSize: '14px',
  },
  value: {
    color: '#1f2937',
    fontSize: '16px',
    fontWeight: '600',
  },
  netSalary: {
    borderTop: '2px solid #3b82f6',
    borderBottom: 'none',
    marginTop: '10px',
    paddingTop: '15px',
    backgroundColor: '#eff6ff',
    marginLeft: '-20px',
    marginRight: '-20px',
    paddingLeft: '20px',
    paddingRight: '20px',
  },
  attendanceInfo: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '10px',
    marginTop: '15px',
    padding: '15px',
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
  },
  attendanceItem: {
    fontSize: '13px',
    color: '#4b5563',
  },
  slipFooter: {
    padding: '15px 20px',
    backgroundColor: '#f9fafb',
    display: 'flex',
    gap: '10px',
  },
  viewButton: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#3b82f6',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
  },
  downloadButton: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#10b981',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '12px',
    maxWidth: '600px',
    width: '90%',
    maxHeight: '90vh',
    overflow: 'auto',
  },
  modalHeader: {
    padding: '20px',
    borderBottom: '1px solid #e5e7eb',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'sticky',
    top: 0,
    backgroundColor: 'white',
    zIndex: 1,
  },
  closeButton: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    color: '#6b7280',
  },
  modalBody: {
    padding: '20px',
  },
  detailSection: {
    marginBottom: '20px',
  },
  sectionTitle: {
    fontSize: '16px',
    color: '#1f2937',
    marginBottom: '10px',
    fontWeight: 'bold',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '8px 0',
    fontSize: '14px',
  },
  netSalaryBox: {
    backgroundColor: '#eff6ff',
    padding: '20px',
    borderRadius: '8px',
    textAlign: 'center',
    marginTop: '20px',
    border: '2px solid #3b82f6',
  },
  finalAmount: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#1f2937',
    marginTop: '10px',
  },
  paidInfo: {
    textAlign: 'center',
    padding: '15px',
    backgroundColor: '#d1fae5',
    color: '#065f46',
    borderRadius: '8px',
    marginTop: '15px',
    fontWeight: '600',
  },
  modalFooter: {
    padding: '20px',
    borderTop: '1px solid #e5e7eb',
    position: 'sticky',
    bottom: 0,
    backgroundColor: 'white',
  },
  downloadButtonLarge: {
    width: '100%',
    padding: '12px',
    backgroundColor: '#10b981',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: '600',
  },
};

export default Payroll;